### ISSUE TITLE
Aliases doesn't work with jbangdev/jbang-action@v0.35.0

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang-action#7]
I have the following configuration:

```yaml
      - name: Index Catalog
        uses: jbangdev/jbang-action@v0.35.0
        with:
          script: indexcatalog@quarkusio
          args: . ./app/registry.json

```

This is the error I get when Github runs it:

```
Run jbangdev/jbang-action@v0.35.0
  with:
    script: indexcatalog@quarkusio
    args: . ./app/registry.json
mkdir: cannot create directory ‘/github/home/.jbang’: Permission denied
[jbang] java.lang.RuntimeException: Invalid alias name ''
[jbang] Run with --verbose for more details

```

**Comment by maxandersen** [comment]
Hmmm...weird as it shouldn't create folders differently than before.

**Comment by maxandersen** [comment]
issue happens because the batch scripts now force create `JBANG_DIR/.cache` even when not needed.

submitted fix/pr that should fix it - publishing as writing this.

**Comment by maxandersen** [comment]
hmm - more to this; the trust stuff apparently never worked in github action ;/

**Comment by maxandersen** [comment]
okey, its non trivial to fix as github actions via dockerfiles are quite rigid. need tothink how work around it.

**Comment by maxandersen** [comment]
believing this is fixed in 0.36.

there is also now a trust parameter you can set to which hosts/urls you want to trust before executing the script.

**Comment by gastaldi** [comment]
Now the directory error is no longer shown, but I still get the same exception. What am I doing wrong?

```
Run jbangdev/jbang-action@v0.36.0
  with:
    script: indexcatalog@quarkusio
    args: . ./app/registry.json
/usr/bin/docker run --name c201b799f604326442879f76d7c68c1c2360_274b62 --label 87c201 --workdir /github/workspace --rm -e INPUT_SCRIPT -e INPUT_ARGS -e INPUT_JBANGARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/quarkus-extension-catalog/quarkus-extension-catalog":"/github/workspace" 87c201:b799f604326442879f76d7c68c1c2360  "" "indexcatalog@quarkusio" ". ./app/registry.json"
[jbang] java.lang.RuntimeException: Invalid alias name ''
[jbang] Run with --verbose for more details
```

**Comment by gastaldi** [comment]
Ah I think there is a bug in the generated command. If I run `jbang "" indexcatalog@quarkusio` I get the same exception

**Comment by maxandersen** [comment]
Hmm. I fixed that. Must be missing a push. Will look tomorrow.

**Comment by maxandersen** [comment]
ok, yes there was a push missing. Changed it so all arguments are done via env variables as github actions doesn't have a way to allow open ended list of arguments. pushing in 0.36.1

**Comment by gastaldi** [comment]
Almost there, now I get:

```
[jbang] Adding [https://github.com/quarkusio/jbang-catalog] to /jbang/.jbang/trusted-sources.json
[jbang] Resolving dependencies...
[jbang]     Resolving info.picocli:picocli:4.2.0...Done
[jbang]     Resolving io.quarkus:quarkus-platform-descriptor-resolver-json:1.7.0.CR1...Done
[jbang]     Resolving com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.1...Done
[jbang] Dependencies resolved
[jbang] Building jar...
Unmatched arguments from index 0: '.', './app/registry.json'
Usage: quarkusindexcatalog [-hV] <repositoryPath> <outputFile>
Indexes a catalog repository to a format read by DefaultExtensionRegistry
      <repositoryPath>   The repository path to index
      <outputFile>       The output file
  -h, --help             Show this help message and exit.
  -V, --version          Print version information and exit.
 ```

**Comment by maxandersen** [comment]
that looks more like an issue in your script/picocoli setup than in the jbang action.

how does your workflow file look like ?

**Comment by gastaldi** [comment]
Here it is: https://github.com/quarkusio/quarkus-extension-catalog/blob/master/.github/workflows/release.yml#L19-L24

I find it weird that it works with `v0.25.0` for example

**Comment by maxandersen** [comment]
did the latest release/build fix this for you or still an issue ?

**Comment by gastaldi** [comment]
No, it is still an issue. I am still investigating what is causing that

**Comment by gastaldi** [comment]
I changed to named parameters and I am getting this now: 

```java
[jbang] Adding [https://github.com/quarkusio/jbang-catalog] to /jbang/.jbang/trusted-sources.json
[jbang] Resolving dependencies...
[jbang]     Resolving info.picocli:picocli:4.5.0...Done
[jbang]     Resolving io.quarkus:quarkus-platform-descriptor-resolver-json:1.7.0.Final...Done
[jbang]     Resolving com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.1...Done
[jbang] Dependencies resolved
[jbang] Building jar...
option '--repository-path' (<repositoryPath>) should be specified only once
Usage: quarkusindexcatalog [-hV] -o=<outputFile> -p=<repositoryPath>
Indexes a catalog repository to a format read by DefaultExtensionRegistry
  -h, --help      Show this help message and exit.
  -o, --output-file=<outputFile>
                  The output file
  -p, --repository-path=<repositoryPath>
                  The repository path to index
  -V, --version   Print version information and exit.

```

**Comment by gastaldi** [comment]
I found the cause: The entrypoint script is wrong:

```
jbang indexcatalog@quarkusio --verbose --repository-path=. --output-file=./app/registry.json --verbose --repository-path=. --output-file=./app/registry.json
```

**Comment by gastaldi** [comment]
Actually this issue is resolved in 0.38.0. The PR fixes the Permission issue, which is another thing. I'll close this now
